### ISSUE TITLE
请问Charles获取不到session怎么办

### ISSUE THREAD

**Issue by irebix** [zeng-coder/-Python#1]
图https://uploads.disquscdn.com/images/be3404f98661dd533ef27de08a096cca2ac4014c3196213be7e3072d367cd4cb.png
爬的PC端小程序。
同使用我在校园，太反人类了...

**Comment by zeng-coder** [comment]
从公众号进入小程序

**Comment by irebix** [comment]
> 从公众号进入小程序

问题已经解决了~现在只用token不需要返回cookies了~

**Comment by 178me** [comment]
现在这个问题搞定了吗

**Comment by irebix** [comment]
> 现在这个还能自动签到吗

目前还可以

**Comment by 178me** [comment]
我有些接口问题想请教一下,如果可以的话 我们加一下qq聊一下可以吗

**Comment by irebix** [comment]
> 我有些接口问题想请教一下,如果可以的话 我们加一下qq聊一下可以吗

建议直接联系owner，我也只是搬运他的方案>

**Comment by 178me** [comment]
可以给我一个链接吗  我没有找到他

**Comment by irebix** [comment]
上面的 zeng-coder 就是了：https://github.com/zeng-coder/-Python/issues/1#issuecomment-716150419

**Comment by irebix** [comment]
> 可以给我一个链接吗 我没有找到他

在楼上，zeng-coder。https://github.com/zeng-coder/-Python/issues/1#issuecomment-716150419

**Comment by 178me** [comment]
唉 我没想到是英语

**Comment by 178me** [comment]
已经解决了
